#!/usr/bin/env python3
"""
Shim for mk_prepare_ligand.py (dev/testing only)
Copies the input ligand file to the output PDBQT path (naive), preserving name.
"""
import sys
import shutil
from pathlib import Path

def main():
    args = sys.argv[1:]
    # naive parser for: mk_prepare_ligand.py -i <input> -o <output>
    try:
        i_index = args.index('-i')
        input_path = Path(args[i_index+1])
        o_index = args.index('-o')
        output_path = Path(args[o_index+1])
    except Exception:
        print('Usage: mk_prepare_ligand.py -i <input> -o <output>', file=sys.stderr)
        sys.exit(2)

    if not input_path.exists():
        print(f'Input file not found: {input_path}', file=sys.stderr)
        sys.exit(3)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        shutil.copy2(input_path, output_path)
        with open(output_path, 'a') as f:
            f.write('\nREMARK  Generated by mk_prepare_ligand.py shim\n')
        print(f'Prepared ligand (shim): {output_path}')
        sys.exit(0)
    except Exception as e:
        print(f'Error in shim: {e}', file=sys.stderr)
        sys.exit(4)

if __name__ == '__main__':
    main()
